import type { EditorThemeClasses } from 'lexical'

export const editorTheme: EditorThemeClasses = {
  // Pasted plain text often contains blank paragraphs between lines.
  // Keep paragraph spacing compact so those blank lines do not create oversized gaps.
  paragraph: 'mb-2 leading-7 text-text-primary',
  heading: {
    h1: 'mt-5 mb-4 border-b border-surface-border-soft pb-2 text-2xl font-bold text-text-primary',
    h2: 'mt-5 mb-3 text-xl font-bold text-text-primary',
    h3: 'mt-4 mb-2 text-lg font-semibold text-text-primary',
  },
  quote: 'border-l-4 border-brand-border pl-4 italic text-text-secondary my-2',
  text: {
    bold: 'font-bold text-text-primary',
    italic: 'italic',
    underline: 'underline',
    strikethrough: 'line-through',
    code: 'bg-surface-muted text-brand-primary px-1.5 py-0.5 rounded text-[0.875em] font-mono',
  },
  list: {
    ul: 'list-disc ml-5 mb-2',
    ol: 'list-decimal ml-5 mb-2',
    listitem: 'mb-0.5 text-text-primary',
    listitemChecked: 'editor-list-item-checked',
    listitemUnchecked: 'editor-list-item-unchecked',
    nested: {
      listitem: 'list-none',
    },
  },
  link: 'text-brand-primary underline hover:brightness-110 cursor-pointer',
  table: 'w-full border-collapse my-3 table-fixed',
  tableRow: '',
  tableCell: 'border border-surface-border px-3 py-2 text-sm text-text-primary align-top min-w-[80px]',
  tableCellHeader: 'border border-surface-border px-3 py-2 text-sm font-semibold text-text-primary align-top',
  tableScrollableWrapper: 'overflow-x-auto my-3',
  code: 'block bg-surface-muted text-text-primary font-mono text-sm p-3 rounded-lg my-2 whitespace-pre-wrap break-words border border-surface-border-soft [overflow-wrap:anywhere]',
  codeHighlight: {
    atrule: 'text-brand-primary',
    attr: 'text-text-primary',
    boolean: 'text-brand-primary',
    builtin: 'text-brand-primary',
    cdata: 'text-text-muted',
    char: 'text-brand-primary',
    class: 'text-brand-primary',
    'class-name': 'text-brand-primary',
    comment: 'text-text-muted italic',
    constant: 'text-brand-primary',
    deleted: 'text-destructive',
    doctype: 'text-text-muted',
    entity: 'text-text-primary',
    function: 'text-text-primary',
    important: 'text-destructive',
    inserted: 'text-brand-primary',
    keyword: 'text-brand-primary font-semibold',
    namespace: 'text-text-secondary',
    number: 'text-brand-primary',
    operator: 'text-text-secondary',
    prolog: 'text-text-muted',
    property: 'text-text-primary',
    punctuation: 'text-text-muted',
    regex: 'text-destructive',
    selector: 'text-brand-primary',
    string: 'text-brand-primary',
    symbol: 'text-brand-primary',
    tag: 'text-destructive',
    url: 'text-brand-primary',
    variable: 'text-destructive',
  },
}
